TagPrefix = "foo"    # comment
ReadBufferSize = 1024

[Receiver]
Host = "localhost"
Port = 24224

[[Servers]]
Host = "127.0.0.1"

[[Servers]]
Host = "127.0.0.1"
Port = 24225

[[Logs]]
Tag  = "tag1"
File = "/tmp/foo.log"

[[Logs]]
Tag  = "tag2"
File = "/tmp/bar.log"
FieldName = "msg"

[Monitor]
Host = "127.0.0.2"
Port = 24223
