TagPrefix = "foo"    # comment

[[Servers]]
Host = "127.0.0.1"

[[Servers]]
Host = "127.0.0.1"
Port = 24225

[[Logs]]
Tag  = "tag1"
File = "/tmp/foo.log"

[[Logs]]
Tag  = "tag2"
File = "/tmp/bar.log"
FieldName = "msg"
